# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
